### ISSUE TITLE
hello,could you tell me how to fix this bug IndexError: index 698 is out of bounds for dimension 0 with size 20

### ISSUE THREAD

**Issue by looker23333** [gaobb/MCAR#1]
this bug is in models.py: xs = wscore[i,gs_ind[j],:].squeeze() when I used voc2007

**Comment by gaobb** [comment]
You could check the shape of $wscore$. Its size should be $b\times c\ times h$.

**Comment by looker23333** [comment]
Okay,thank you,I'll try it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaobb/MCAR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月18日(星期天) 晚上11:23
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [gaobb/MCAR] hello,could you tell me how to fix this bug IndexError: index 698 is out of bounds for dimension 0 with size 20 (#1)





 
You can check the shape of wscore. Its size should be $bch$.
