### ISSUE TITLE
Attention Map

### ISSUE THREAD

**Issue by yjj-liwei** [gaobb/MCAR#5]
![image](https://user-images.githubusercontent.com/73466929/159829217-ecc48944-ce9d-4fec-9013-1878066a8820.png)
请问您论文中这个可视化图的代码能够提供吗？谢谢啦！！！

**Comment by gaobb** [comment]
hi, thanks for your attention.  The visualization can be done in the following three steps:

First, for the class-specific attention map visualization, you can refer to the [CAM](https://github.com/zhoubolei/CAM);
Second, the marginal distributions over x- and y-axis can be easily obtained by Eq. 6 in our paper once you get the above class-specific attention map;
Third, the local region localization~(bounding box) can be visualized by using the following codes including this repository. https://github.com/gaobb/MCAR/blob/master/src/mcar_demo.py#L127
https://github.com/gaobb/MCAR/blob/master/src/util.py#L105-L125

**Comment by yjj-liwei** [comment]
十分感谢您耐心的解答！受益匪浅！感谢
