### ISSUE TITLE
candidate regions diversity

### ISSUE THREAD

**Issue by yjj-liwei** [gaobb/MCAR#6]
The category of boxes that get multiple regions in your code is not duplicated to ensure diversity. 
At present, I want to allow multiple boxes to have the same class. Where should I start with this part of the code!
Thanks you！

**Comment by gaobb** [comment]
hi, thanks very much for your attention to our work. 

The diversity of candidate regions is ensured by the class activation mapping method. (Eq. 4 in our paper). 
https://github.com/gaobb/MCAR/blob/master/src/models.py#L139-L140
