### ISSUE TITLE
the divesity of candidate regions

### ISSUE THREAD

**Issue by yjj-liwei** [gaobb/MCAR#7]
How the candidate region diversity is implemented in the code？
Thanks you！

**Comment by gaobb** [comment]
please see https://github.com/gaobb/MCAR/issues/6

**Comment by gaobb** [comment]
please see https://github.com/gaobb/MCAR/issues/6

**Comment by gaobb** [comment]
Duplicate of #https://github.com/gaobb/MCAR/issues/6
