### ISSUE TITLE
mobilenetv2_1.0-0c6065bc.pth

### ISSUE THREAD

**Issue by XZNWU** [gaobb/MCAR#8]
Great work, can you share the download address of the pre-trained model mobilenetv2_1.0-0c6065bc.pth？

**Comment by gaobb** [comment]
You can free download the pre-trained model mobilenetv2_1.0-0c6065bc.pth from [mobilenetv2.pytorch](https://github.com/d-li14/mobilenetv2.pytorch/blob/master/pretrained/mobilenetv2_1.0-0c6065bc.pth)

 pre-trained model

**Comment by XZNWU** [comment]
Thank you so much.
